<div id="fh5co-header">
    <div class="container">
        <!-- Mobile Toggle Menu Button -->
        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
        <div id="fh5co-logo">
            <a href="index.html">VERA<span>.</span></a>
        </div>
        <nav id="fh5co-main-nav">
            <ul>
                <li><a href="#" data-nav-section="home">Главная</a></li>
                <li><a href="#" data-nav-section="review">Отзывы</a></li>
                <li><a href="#" data-nav-section="contact">Контакты</a></li>
            </ul>
        </nav>
    </div>
</div>
<div id="fh5co-main">
    <div class="fh5co-overlay-mobile"></div>
    <div id="fh5co-home" class="js-fullheight" data-section="home">
        <div class="flexslider">
            <ul class="slides">
                <li style="background-image: url(images/slide_2.jpg);" data-stellar-background-ratio="0.5">
                    <div class="fh5co-overlay"></div>
                    <div class="fh5co-text">
                        <div class="container">
                            <div class="row text-center">
                                <h1 class="animate-box">Доверьте нам свой гардероб</h1>
                                <div class="fh5co-go animate-box">
                                    <a href="#" class="js-fh5co-next">
                                        хочу доверить
                                        <span><i class="icon-arrow-down2"></i></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li style="background-image: url(images/slide_1.jpg);" data-stellar-background-ratio="0.5">
                    <div class="fh5co-overlay"></div>
                    <div class="fh5co-text">
                        <div class="container">
                            <div class="row text-center">
                                <h1 class="animate-box">Покупайте меньше, выбирайте лучше, и делайте это
                                    самостоятельно.</h1>
                                <div class="fh5co-go animate-box">
                                    <a href="#" class="js-fh5co-next">
                                        хочу лучшее
                                        <span><i class="icon-arrow-down2"></i></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li style="background-image: url(images/slide_3.jpg);" data-stellar-background-ratio="0.5">
                    <div class="fh5co-overlay"></div>
                    <div class="fh5co-text">
                        <div class="container">
                            <div class="row text-center">
                                <h1 class="animate-box">Мы не создаем одежду, мы воплощаем мечты.</h1>
                                <div class="fh5co-go animate-box">
                                    <a href="#" class="js-fh5co-next">
                                        хочу воплотить
                                        <span><i class="icon-arrow-down2"></i></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>

        </div>
    </div>

    <div id="fh5co-portfolio" data-section="review">
        <div class="container">
            <div class="row r-pb">
                <div class="col-md-8 col-md-offset-2 text-center section-heading">
                    <h2 class="fh5co-section-title animate-box">ОТЗЫВЫ</h2>
                    <p class="fh5co-lead animate-box">Вводный текст</p>
                </div>
            </div>
            <div id="gallery" class="row">
                <?php for($i = 1; $i<13; $i++):?>
                    <div class="gallery-item col-md-4 col-sm-4 col-xs-6 col-xxs-12 animate-box">
                        <div class="img-grid">
                            <img src="images/pic_<?php echo $i?>.jpg" alt="" class="img-responsive">
                            <a href="#" class="transition">
                                <div>
                                    <span class="fh5co-meta"><?php echo $i?> картина</span>
                                    <h2 class="fh5co-title">отзыв</h2>
                                </div>
                            </a>
                        </div>
                    </div>
                <?php endfor;?>
            </div>
        </div>

        <div id="fh5co-contact" data-section="contact">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center section-heading">
                        <h2 class="fh5co-section-title animate-box">КОНТАКТЫ</h2>
                        <p class="fh5co-lead animate-box"> Какие-то контакты </p>
                        <p class="animate-box"> </p>
                        <p class="animate-box"><a href="" target="" class="btn btn-primary btn-lg">Заказать звонок</a></p>
                    </div>
                </div>
            </div>
        </div>

        <div id="fh5co-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 animate-box">
                        <div class="fh5co-footer-widget">
                            <p>Created by Jahangir Ereshov</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 animate-box">
                        <div class="fh5co-footer-widget">
                            <ul class="fh5co-social pull-right">
                                <li>
                                    <a href="https://www.vk.com/id166415916"><i class="icon-vk"></i></a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/atelierno1_astana/?hl=ru"><i class="icon-instagram"></i></a>
                                </li>
                            </ul>
                            <div class="fh5co-footer-widget">
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div><!-- END fh5co-page -->

