<div id="fh5co-about"  data-section="about">
    <div class="container">
        <div class="row r-pb">
            <div class="col-md-8 col-md-offset-2 text-center section-heading animate-box">
                <h2 class="fh5co-section-title">О нас</h2>
                <p class="fh5co-lead">
                    Atelier №1 шьёт одежду по доступным ценам, наш главный принцип - это качество.
                    Высокие стандарты качества задает наш мастер-портной.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-2 text-center animate-box">
                <span class="imageMaster">
                    <img src="images/vera.jpg" alt="" />
                </span>
            </div>
            <div class="col-md-4 animate-box">
                <div class="fh5co-text">
                    <h2>Вера Зейнулловна</h2>
                    <span class="fh5co-meta">Мастер-портной</span>
                    <p>" - Мне важно в создании одежды достичь совершенства."</p>
                </div>
            </div>
        </div>
    </div>
</div>