<div id="fh5co-contact" data-section="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center section-heading">
                <h2 class="fh5co-section-title animate-box">КОНТАКТЫ</h2>
<!--                <p class="fh5co-lead animate-box"> .</p>-->
                <p class="animate-box">Вера Зейнуловна портной высшего класса с многолетним опытом, её главный принцип - качество. С ней сотрудничают
                            как модельеры с мировым именем так и астанинские жители.</p>
                </p>
            </div>
            <div class="col-md-12 col-md-offset-1">
                <div class="row">
                    <p class="col-md-4 col-md-offset-1 animate-box">
                        <a class = "contact-icon-size icon-active" href="#"><i class="icon-phone"></i></a>
                        <b>Телефон:</b> +7(708)765-70-70
                    </p>
                    <p class="col-md-4 col-md-offset-1 animate-box">
                        <a class = "contact-icon-size icon-active" href="#"><i class="icon-mail"></i></a>
                        <b>Почта:</b> altin-14@mail.ru
                    </p>
                </div>
                <div class="row">
                    <p class="col-md-4 col-md-offset-1 animate-box">
                        <a class = "contact-icon-size icon-active" href="#"><i class="icon-location"></i></a>
                        <b>Адрес:</b> г. Астана ул. Шевченко д. 10
                    </p>
                    <p class="col-md-4 col-md-offset-1 animate-box">
                        <a class = "contact-icon-size icon-active" href="#"><i class="icon-clock3"></i></a>
                        <b>Часы работы:</b> 9:00-18:00 <br>(без перерывов и выходных)
                    </p>
                </div>
            </div>

            <div class="col-md-8 col-md-offset-3 animate-box">
                <div class="fh5co-footer-widget">
                    <ul class="fh5co-social pull-right">
                        <li>
                            <a href="https://www.instagram.com/atelier_astana1/"><i class="icon-instagram"></i></a>
                        </li>
                    </ul>
                    <div class="fh5co-footer-widget">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
/**
 * Created by PhpStorm.
 * User: jahangir
 * Date: 19.02.18
 * Time: 1:46
 */