<div class="fh5co-overlay-mobile"></div>
<div id="fh5co-home" class="js-fullheight" data-section="home">
    <div class="flexslider">
        <div class="fh5co-overlay"></div>
        <div class="fh5co-text">
            <div class="container">
                <div class="row text-center">
                    <h1 class="animate-box">ATELIER VERA IBRAEVA</h1>
                    <div class="fh5co-go animate-box">
                        <a href="#" class="js-fh5co-next">
                            Контакты
                            <span><i class="icon-arrow-down2"></i></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <ul class="slides">
            <li style="background-image: url(images/slide_2.jpg);" data-stellar-background-ratio="0.5"></li>
            <li style="background-image: url(images/slide_1.jpg);" data-stellar-background-ratio="0.5"></li>
            <li style="background-image: url(images/slide_3.jpg);" data-stellar-background-ratio="0.5"></li>
        </ul>
    </div>
</div>
<?php
/**
 * Created by PhpStorm.
 * User: jahangir
 * Date: 19.02.18
 * Time: 1:50
 */